name: adstream
version: 1.7.0
config-version: 2
profile: adstream
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  adstream:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
